# Generated by Django 3.2 on 2021-04-11 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('movie_kind', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romantic', 'Romantic'), ('Adventure', 'Adventure'), ('Musical', 'Musical'), ('Drama', 'Drama'), ('Historical', 'Historical'), ('Real life', 'Real life'), ('War', 'War'), ('Honor', 'Honor'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller')], max_length=200)),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('Spanish', 'Spanish')], max_length=200)),
                ('first_screening_date', models.DateField()),
                ('imdb_url', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('imdb_grading', models.FloatField()),
                ('imdb_summary', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('grading', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('nationality', models.CharField(choices=[('American', 'American'), (' Czechoslovakian', ' Czechoslovakian'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('New Zealand', 'New Zealand'), ('Spanish', 'Spanish')], max_length=200)),
                ('birthday', models.DateField()),
                ('resume', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.moviedetails')),
                ('movie_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.moviedirector')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.moviedirector'),
        ),
    ]
