# Generated by Django 3.2 on 2021-04-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie_director',
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_kind',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romantic', 'Romantic'), ('Adventure', 'Adventure'), ('Musical', 'Musical'), ('Drama', 'Drama'), ('Historical', 'Historical'), ('Real life', 'Real life'), ('War', 'War'), ('Horror', 'Horror'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Biographical', 'Biographical'), ('Feature', 'Feature'), ('Satirical', 'Satirical'), ('Dystopian', 'Dystopian')], max_length=200),
        ),
    ]
