# Generated by Django 3.2 on 2021-04-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.moviedirector'),
        ),
        migrations.AlterField(
            model_name='post',
            name='movie_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.moviedetails'),
        ),
    ]
